"""
design_compiler.py
End-to-end PCB design compiler.

Takes a natural-language prompt, runs the full pipeline:
  1. Parse requirements (LLM via Anna sampling, or local keyword fallback)
  2. Generate BOM from requirements
  3. Write KiCad schematic (.kicad_sch) from BOM
  4. Write KiCad PCB layout (.kicad_pcb) from BOM via pcbnew
  5. Export Gerbers via kicad-cli
  6. Package everything into a ZIP

The output changes with every different prompt — the BOM, schematic,
and board topology are all derived from what the user asked for.
"""

from __future__ import annotations

import json
import os
import subprocess
import zipfile
from typing import List, Dict, Any

from pcbai.steps.requirements_parser import parse_requirements
from pcbai.steps.bom_generator import generate_bom


def _build_schematic_from_bom(bom: List[Dict], output_path: str, prompt: str) -> None:
    """
    Generate a minimal but valid KiCad 6 schematic that lists every BOM entry
    as a symbol with correct Reference, Value, and Footprint properties.

    No pcbnew dependency — pure string generation.
    """
    import uuid

    def _uid() -> str:
        return str(uuid.uuid4())

    def _passive_body() -> str:
        return (
            "      (rectangle (start -1.016 0.762) (end 1.016 -0.762)\n"
            "        (stroke (width 0.254) (type default))\n"
            "        (fill (type background))\n"
            "      )\n"
            "      (pin passive line (at -2.54 0 0) (length 2.54)\n"
            "        (name \"~\" (effects (font (size 1.27 1.27))))\n"
            "        (number \"1\" (effects (font (size 1.27 1.27))))\n"
            "      )\n"
            "      (pin passive line (at 2.54 0 180) (length 2.54)\n"
            "        (name \"~\" (effects (font (size 1.27 1.27))))\n"
            "        (number \"2\" (effects (font (size 1.27 1.27))))\n"
            "      )\n"
        )

    def _ic_body(npins: int = 4) -> str:
        pins_per_side = (npins + 1) // 2
        h = max(5.08, pins_per_side * 2.54 + 2.54)
        body = (
            f"      (rectangle (start -10.16 {h/2:.2f}) (end 10.16 {-h/2:.2f})\n"
            "        (stroke (width 0.254) (type default))\n"
            "        (fill (type background))\n"
            "      )\n"
        )
        for i in range(npins):
            side = 0 if i < pins_per_side else 1
            idx = i if side == 0 else (i - pins_per_side)
            y = h / 2 - 2.54 - idx * 2.54
            
            if side == 0:
                body += (
                    f"      (pin bidirectional line (at -12.70 {y:.2f} 0) (length 2.54)\n"
                    f"        (name \"IO{i}\" (effects (font (size 1.27 1.27))))\n"
                    f"        (number \"{i+1}\" (effects (font (size 1.27 1.27))))\n"
                    "      )\n"
                )
            else:
                body += (
                    f"      (pin bidirectional line (at 12.70 {y:.2f} 180) (length 2.54)\n"
                    f"        (name \"IO{i}\" (effects (font (size 1.27 1.27))))\n"
                    f"        (number \"{i+1}\" (effects (font (size 1.27 1.27))))\n"
                    "      )\n"
                )
        return body

    # Decide symbol body per package class
    def _body_for(pkg: str, pins: int = 0) -> str:
        if pins > 2:
            return _ic_body(pins)
        
        pkg_lower = pkg.lower()
        if any(k in pkg_lower for k in ["module", "lqfp", "qfn", "lga", "soc", "mcu"]):
            return _ic_body(8)
        elif any(k in pkg_lower for k in ["soic-8", "soic8"]):
            return _ic_body(8)
        elif any(k in pkg_lower for k in ["sot-23", "sot23", "sot-223"]):
            return _ic_body(3)
        elif any(k in pkg_lower for k in ["usb"]):
            return _ic_body(5)
        else:
            return _passive_body()

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)

    lines: List[str] = []
    lines.append(
        "(kicad_sch\n"
        "  (version 20231120)\n"
        "  (generator \"pcbai\")\n"
        "  (generator_version \"1.1.0\")\n"
        f"  (uuid \"{_uid()}\")\n"
        "  (paper \"A3\")\n"
        "  (title_block\n"
        f"    (title \"{prompt[:60].replace(chr(34), '')}\")\n"
        "    (rev \"v1.0\")\n"
        "    (company \"pcb-designer-ai-agent\")\n"
        "    (comment 1 \"Auto-generated by pcbai — output reflects user prompt\")\n"
        "  )\n"
    )

    # Inline lib_symbols — one symbol per unique package class
    seen_syms: set = set()
    lib_body = "  (lib_symbols\n"
    for comp in bom:
        pkg = comp.get("package", "0805")
        pins = int(comp.get("pins", 0))
        sym_name = _safe_sym(pkg)
        if sym_name not in seen_syms:
            seen_syms.add(sym_name)
            body = _body_for(pkg, pins)
            lib_body += (
                f"    (symbol \"pcbai:{sym_name}\"\n"
                "      (pin_names (offset 1.016))\n"
                "      (in_bom yes) (on_board yes)\n"
                f"      (symbol \"{sym_name}_0_1\"\n"
                f"{body}"
                "      )\n"
                "    )\n"
            )
    lib_body += "  )\n"
    lines.append(lib_body)

    # Place component instances on a grid
    COLS = 4
    X_STEP = 45.0
    Y_STEP = 35.0
    for idx, comp in enumerate(bom):
        col = idx % COLS
        row = idx // COLS
        x = 30.0 + col * X_STEP
        y = 30.0 + row * Y_STEP
        ref = comp.get("ref", f"U{idx+1}")
        mpn = comp.get("mpn", "UNKNOWN")
        pkg = comp.get("package", "0805")
        sym_name = _safe_sym(pkg)
        fp = comp.get("footprint", "")
        uid = _uid()
        lines.append(
            f"  (symbol (lib_id \"pcbai:{sym_name}\") (at {x} {y} 0)\n"
            "    (unit 1)\n"
            "    (in_bom yes) (on_board yes) (dnp no)\n"
            f"    (uuid \"{uid}\")\n"
            f"    (property \"Reference\" \"{ref}\" (at {x} {y - 4} 0)\n"
            "      (effects (font (size 1.27 1.27)))\n"
            "    )\n"
            f"    (property \"Value\" \"{mpn}\" (at {x} {y + 4} 0)\n"
            "      (effects (font (size 1.27 1.27)))\n"
            "    )\n"
            f"    (property \"Footprint\" \"{fp}\" (at {x} {y} 0)\n"
            "      (effects (font (size 1.27 1.27)) hide)\n"
            "    )\n"
            f"    (property \"Description\" \"{comp.get('description', '')}\" (at {x} {y} 0)\n"
            "      (effects (font (size 1.27 1.27)) hide)\n"
            "    )\n"
            "  )\n"
        )

    lines.append(")\n")

    with open(output_path, "w", encoding="utf-8") as fh:
        fh.writelines(lines)
    print(f"[design_compiler] Wrote schematic → {output_path}")


def _safe_sym(pkg: str) -> str:
    """Turn a package string into a valid KiCad symbol name (no spaces/slashes)."""
    import re
    return re.sub(r"[^A-Za-z0-9_-]", "_", pkg)[:40]


def _build_pcb_from_bom(bom: List[Dict], output_path: str, prompt: str) -> bool:
    """
    Generate a .kicad_pcb file driven entirely by *bom*.

    Falls back to a plain-text placeholder when pcbnew is unavailable
    (so the pipeline still produces a file — the Anna tester gets a
    clear error message instead of a silent fixed board).
    """
    import sys

    _KICAD_LIB = "/usr/lib/python3/dist-packages"
    if _KICAD_LIB not in sys.path:
        sys.path.insert(0, _KICAD_LIB)

    try:
        import pcbnew
        _ok = True
    except ImportError:
        _ok = False

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)

    if not _ok:
        # Write a human-readable placeholder — testers see the error clearly
        with open(output_path, "w", encoding="utf-8") as fh:
            fh.write(
                "; pcbnew not available on this system.\n"
                "; Install KiCad 8 and re-run on a Local Agent.\n"
                f"; Prompt was: {prompt}\n"
                f"; BOM had {len(bom)} components: "
                + ", ".join(c.get("mpn", "?") for c in bom)
                + "\n"
            )
        print("[design_compiler] pcbnew unavailable — wrote placeholder PCB file.")
        return False

    # ── pcbnew is available: build a real board ───────────────────────────────
    def mm(v: float) -> int:
        return pcbnew.FromMM(v)

    def pt(x: float, y: float):
        return pcbnew.VECTOR2I(mm(x), mm(y))

    # Board dimensions — scale with component count
    n = len(bom)
    COLS = max(2, min(5, n))
    ROWS = (n + COLS - 1) // COLS
    STEP = 20.0          # mm between component centres
    MARGIN = 10.0
    BW = MARGIN * 2 + COLS * STEP
    BH = MARGIN * 2 + ROWS * STEP

    board = pcbnew.BOARD()

    tb = board.GetTitleBlock()
    tb.SetTitle(prompt[:80])
    tb.SetRevision("v1.0")
    tb.SetCompany("pcb-designer-ai-agent")

    try:
        board.GetStackup().SetBoardThickness(mm(1.6))
    except Exception:
        pass

    # Board outline
    corners = [(0, 0), (BW, 0), (BW, BH), (0, BH), (0, 0)]
    for i in range(len(corners) - 1):
        seg = pcbnew.PCB_SHAPE(board)
        seg.SetShape(pcbnew.SHAPE_T_SEGMENT)
        seg.SetLayer(pcbnew.Edge_Cuts)
        seg.SetWidth(mm(0.05))
        seg.SetStart(pt(*corners[i]))
        seg.SetEnd(pt(*corners[i + 1]))
        board.Add(seg)

    # Add GND net
    gnd_net = pcbnew.NETINFO_ITEM(board, "GND", 1)
    board.Add(gnd_net)
    vcc_net = pcbnew.NETINFO_ITEM(board, "+3V3", 2)
    board.Add(vcc_net)
    board.BuildListOfNets()

    FP_LIB_ROOT = "/usr/share/kicad/footprints"

    def _load_fp(lib: str, fp_name: str):
        lib_path = os.path.join(FP_LIB_ROOT, f"{lib}.pretty")
        try:
            return pcbnew.FootprintLoad(lib_path, fp_name)
        except Exception:
            return None

    def _make_placeholder(ref: str, value: str) -> "pcbnew.FOOTPRINT":
        fp = pcbnew.FOOTPRINT(board)
        fp.SetFPID(pcbnew.LIB_ID("pcbai", value[:40]))
        for i, dx in enumerate([-1.0, 1.0]):
            pad = pcbnew.PAD(fp)
            pad.SetShape(pcbnew.PAD_SHAPE_RECT)
            pad.SetAttribute(pcbnew.PAD_ATTRIB_SMD)
            lset = pcbnew.LSET()
            lset.addLayer(pcbnew.F_Cu)
            lset.addLayer(pcbnew.F_Paste)
            lset.addLayer(pcbnew.F_Mask)
            pad.SetLayerSet(lset)
            pad.SetSize(pcbnew.VECTOR2I(mm(0.8), mm(0.8)))
            pad.SetPosition(pcbnew.VECTOR2I(mm(dx), 0))
            pad.SetNumber(str(i + 1))
            fp.Add(pad)
        return fp

    def _make_parametric_footprint(ref: str, mpn: str, pkg: str) -> "pcbnew.FOOTPRINT":
        """Use LLM to fetch datasheet parameters and build footprint parametrically!"""
        from pcbai.llm.provider import get_provider
        import json
        import re
        
        prompt = f"I need physical package parameters for MPN '{mpn}' in package '{pkg}'. Return ONLY a JSON object with: 'pitch' (mm), 'body_w' (mm), 'body_l' (mm), 'pins' (int), 'pad_w' (mm), 'pad_l' (mm). Guess standard values if exact datasheet isn't memorized."
        provider = get_provider()
        try:
            raw = provider.chat([{"role": "user", "content": prompt}], temperature=0.1)
            
            # Robust JSON object extraction
            match = re.search(r'\{.*\}', raw, re.DOTALL)
            if match:
                raw = match.group(0)
            else:
                raw = raw.strip()
                if "```" in raw: raw = raw.split("```")[1]
                if raw.startswith("json"): raw = raw[4:]
                
            params = json.loads(raw.strip())
        except Exception as e:
            print(f"[parametric_fp] LLM failed for {mpn}, falling back to placeholder. {e}")
            return _make_placeholder(ref, mpn)
            
        pitch = float(params.get("pitch", 0.5))
        body_w = float(params.get("body_w", 5.0))
        pins = int(params.get("pins", 8))
        pad_w = float(params.get("pad_w", 0.3))
        pad_l = float(params.get("pad_l", 1.0))
        
        fp = pcbnew.FOOTPRINT(board)
        fp.SetFPID(pcbnew.LIB_ID("pcbai", f"{pkg}_{pins}"))
        
        lset = pcbnew.LSET()
        lset.addLayer(pcbnew.F_Cu)
        lset.addLayer(pcbnew.F_Paste)
        lset.addLayer(pcbnew.F_Mask)
        
        pins_per_side = max(1, pins // 2)
        start_y = -((pins_per_side - 1) * pitch) / 2
        
        for i in range(pins):
            pad = pcbnew.PAD(fp)
            pad.SetShape(pcbnew.PAD_SHAPE_RECT)
            pad.SetAttribute(pcbnew.PAD_ATTRIB_SMD)
            pad.SetLayerSet(lset)
            pad.SetSize(pcbnew.VECTOR2I(mm(pad_l), mm(pad_w)))
            
            side = 0 if i < pins_per_side else 1
            idx = i if side == 0 else (pins - 1 - i)
            
            x = -body_w/2 if side == 0 else body_w/2
            y = start_y + idx * pitch
            
            pad.SetPosition(pcbnew.VECTOR2I(mm(x), mm(y)))
            pad.SetNumber(str(i + 1))
            fp.Add(pad)
            
        print(f"[parametric_fp] AI Generated {pkg} footprint for {mpn} with {pins} pins!")
        return fp

    # Map our BOM package strings to KiCad footprint libraries
    FOOTPRINT_MAP = {
        "Module":   ("RF_Module",          "ESP32-WROOM-32"),
        "LQFP-48":  ("Package_QFP",        "LQFP-48_7x7mm_P0.5mm"),
        "SOIC-8":   ("Package_SO",         "SOIC-8_3.9x4.9mm_P1.27mm"),
        "SOT-223":  ("Package_TO_SOT_SMD", "SOT-223-3_TabPin2"),
        "USB-C-SMD":("Connector_USB",      "USB_C_Receptacle_Molex_2011640100"),
        "SMD":      ("Capacitor_SMD",      "C_0805_2012Metric"),
        "0805":     ("Capacitor_SMD",      "C_0805_2012Metric"),
        "0402":     ("Resistor_SMD",       "R_0402_1005Metric"),
    }

    for idx, comp in enumerate(bom):
        col = idx % COLS
        row = idx // COLS
        x = MARGIN + col * STEP + STEP / 2
        y = MARGIN + row * STEP + STEP / 2

        ref = comp.get("ref", f"U{idx+1}")
        value = comp.get("mpn", "UNKNOWN")
        pkg = comp.get("package", "0805")

        # Try to load real footprint
        fp = None
        if pkg in FOOTPRINT_MAP:
            lib, fp_name = FOOTPRINT_MAP[pkg]
            fp = _load_fp(lib, fp_name)

        if fp is None:
            if pkg != "UNKNOWN" and pkg != "0805":
                fp = _make_parametric_footprint(ref, value, pkg)
            else:
                fp = _make_placeholder(ref, value)

        board.Add(fp)
        fp.SetReference(ref)
        fp.SetValue(value)
        fp.SetPosition(pt(x, y))
        fp.SetOrientationDegrees(0)

        # Assign GND/VCC to first two pads
        pads = list(fp.Pads())
        if len(pads) >= 1:
            pads[0].SetNet(gnd_net)
        if len(pads) >= 2:
            pads[1].SetNet(vcc_net)

        print(f"[design_compiler] Placed {ref} ({value}) at ({x:.1f}, {y:.1f}) pkg={pkg}")

    # Save board iteratively before attempting high-risk operations (copper pour)
    pcbnew.SaveBoard(output_path, board)
    print(f"[design_compiler] Saved intermediate PCB with all components → {output_path}")

    # GND pour on F.Cu
    zone = pcbnew.ZONE(board)
    zone.SetNet(gnd_net)
    zone.SetLayer(pcbnew.F_Cu)
    zone.SetZoneName("GND_pour")
    zone.SetMinThickness(mm(0.127))
    zone.SetPadConnection(pcbnew.ZONE_CONNECTION_THERMAL)
    outline = zone.Outline()
    outline.NewOutline()
    for px, py in [(0, 0), (BW, 0), (BW, BH), (0, BH)]:
        outline.Append(mm(px), mm(py))
    board.Add(zone)

    try:
        filler = pcbnew.ZONE_FILLER(board)
        filler.Fill(board.Zones())
    except Exception as e:
        print(f"[design_compiler] Zone fill skipped: {e}")

    pcbnew.SaveBoard(output_path, board)
    print(f"[design_compiler] Saved PCB → {output_path}")
    return True


def compile_design(prompt: str, output_dir: str) -> dict:
    """
    Full pipeline: prompt → BOM → schematic + PCB → Gerbers → ZIP.

    Returns a dict with keys: bom, sch, pcb, gerbers, zip.
    Raises RuntimeError with a clear message if pcbnew is not available.
    """
    os.makedirs(output_dir, exist_ok=True)

    # ── Step 1: Parse requirements ────────────────────────────────────────────
    print(f"[design_compiler] Parsing requirements for: {prompt[:80]}")
    requirements = parse_requirements(prompt)
    print(f"[design_compiler] Keywords extracted: {requirements.get('keywords', [])}")

    # ── Step 2: Generate BOM ──────────────────────────────────────────────────
    raw_bom = generate_bom(requirements)

    # Enrich BOM entries with ref designators and footprint hints
    bom: List[Dict[str, Any]] = []
    ref_counters: Dict[str, int] = {}
    for entry in raw_bom:
        pkg = entry.get("package", "0805")
        # Assign ref designator prefix by package class
        prefix = _ref_prefix(pkg)
        ref_counters[prefix] = ref_counters.get(prefix, 0) + 1
        ref = f"{prefix}{ref_counters[prefix]}"
        enriched = dict(entry)
        enriched["ref"] = ref
        enriched["footprint"] = _footprint_str(pkg)
        enriched.setdefault("description", enriched.get("mpn", ""))
        bom.append(enriched)

    bom_path = os.path.join(output_dir, "bom.json")
    with open(bom_path, "w") as f:
        json.dump(bom, f, indent=2)
    print(f"[design_compiler] BOM: {len(bom)} components → {bom_path}")

    # ── Step 3: Schematic ─────────────────────────────────────────────────────
    sch_path = os.path.join(output_dir, "schematic.kicad_sch")
    _build_schematic_from_bom(bom, sch_path, prompt)

    # ── Step 4: PCB ───────────────────────────────────────────────────────────
    pcb_path = os.path.join(output_dir, "board.kicad_pcb")
    pcb_ok = _build_pcb_from_bom(bom, pcb_path, prompt)

    if not pcb_ok:
        raise RuntimeError(
            "pcbnew (KiCad 8 Python API) is not installed on this system. "
            "This app requires a Local Agent with KiCad 8. "
            "Please install KiCad 8 from https://www.kicad.org/download/ and re-run."
        )

    # ── Step 5: Project file ──────────────────────────────────────────────────
    pro_path = os.path.join(output_dir, "project.kicad_pro")
    with open(pro_path, "w") as f:
        f.write('{"board": {"design_settings": {}}}')

    # ── Step 6: Gerber export ─────────────────────────────────────────────────
    gerbers_dir = os.path.join(output_dir, "gerbers")
    os.makedirs(gerbers_dir, exist_ok=True)
    try:
        subprocess.run(
            ["kicad-cli", "pcb", "export", "gerbers",
             "--output", gerbers_dir, pcb_path],
            check=True, capture_output=True, timeout=60,
        )
        print(f"[design_compiler] Gerbers exported → {gerbers_dir}")
    except Exception as e:
        print(f"[design_compiler] Gerber export skipped: {e}")

    # ── Step 7: ZIP ───────────────────────────────────────────────────────────
    zip_path = os.path.join(output_dir, "pcb_project.zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for fpath in [bom_path, sch_path, pcb_path, pro_path]:
            if os.path.exists(fpath):
                zf.write(fpath, os.path.basename(fpath))
        for root, _, files in os.walk(gerbers_dir):
            for fname in files:
                abs_path = os.path.join(root, fname)
                rel_path = os.path.relpath(abs_path, output_dir)
                zf.write(abs_path, rel_path)
    print(f"[design_compiler] ZIP → {zip_path}")

    return {
        "bom": bom,
        "sch": sch_path,
        "pcb": pcb_path,
        "gerbers": gerbers_dir,
        "zip": zip_path,
    }


# ── Helpers ───────────────────────────────────────────────────────────────────

def _ref_prefix(pkg: str) -> str:
    pkg_lower = pkg.lower()
    if any(k in pkg_lower for k in ["module", "lqfp", "qfn", "lga", "soc"]):
        return "U"
    elif "soic" in pkg_lower:
        return "U"
    elif "sot" in pkg_lower:
        return "U"
    elif "usb" in pkg_lower:
        return "J"
    elif "led" in pkg_lower:
        return "D"
    else:
        return "U"


def _footprint_str(pkg: str) -> str:
    """Return a KiCad footprint reference string for the given package."""
    FOOTPRINT_STR_MAP = {
        "Module":    "RF_Module:ESP32-WROOM-32",
        "LQFP-48":  "Package_QFP:LQFP-48_7x7mm_P0.5mm",
        "SOIC-8":   "Package_SO:SOIC-8_3.9x4.9mm_P1.27mm",
        "SOT-223":  "Package_TO_SOT_SMD:SOT-223-3_TabPin2",
        "USB-C-SMD":"Connector_USB:USB_C_Receptacle_Molex_2011640100",
        "SMD":      "Capacitor_SMD:C_0805_2012Metric",
        "0805":     "Capacitor_SMD:C_0805_2012Metric",
        "0402":     "Resistor_SMD:R_0402_1005Metric",
    }
    return FOOTPRINT_STR_MAP.get(pkg, f"pcbai:{_safe_sym(pkg)}")
